### ISSUE TITLE
Sticky table headers on desktop

### ISSUE THREAD

**Issue by Carlgo11** [2factorauth/dev#10]

**Comment by Carlgo11** [comment]
Fixed in Firefox & Safari. Doesn't work in Chromium browsers due to https://bugs.chromium.org/p/chromium/issues/detail?id=370155

**Comment by jamcat22** [comment]
Can we use the same fix used in 2factorauth/twofactorauth#4746?

**Comment by Carlgo11** [comment]
Sadly not 😕
