### ISSUE TITLE
Add build date?

### ISSUE THREAD

**Issue by Carlgo11** [2factorauth/dev#11]
- I see that the build number is listed. Would we be able to add the build date as well?
- Would help people see if they're viewing latest changes.

Created by @jamcat22

**Comment by Carlgo11** [comment]
Looked around and it seems like there's no way to get any data about the build revision other than the SHA1 hash. As such the only way to see if you're using the latest version would be to compare the hashes.

**Comment by jamcat22** [comment]
What if we just use Jekyll's `site.time` and truncate it to the date? Pretty sure the time is set only when the Jekyll command is run, which I'm pretty sure happens only once per deployment on GitHub Pages. It's set for UTC+0.

Seems to work on 2fa.gmcd.co.

**Comment by Carlgo11** [comment]
Alright. Yeah that would work

**Comment by Carlgo11** [comment]
@jamcat22 See current build (You might need to clear cache)

**Comment by jamcat22** [comment]
👍
Do we want to just display the date (`slice 0,10`), or include both date and time?

**Comment by Carlgo11** [comment]
Same info is found in the file headers
![firefox_8AUGPlCiLt](https://user-images.githubusercontent.com/3535780/81670113-6ec1b980-9447-11ea-969b-07900c8bfc3c.png)
