### ISSUE TITLE
JavaScript warning if disabled

### ISSUE THREAD

**Issue by jamcat22** [2factorauth/dev#9]
![twofactorauth v2 JavaScript Warning](https://user-images.githubusercontent.com/1897053/81573069-3f388180-9361-11ea-9207-0b22b94f8362.png)
Or just get rid of all the JavaScript! 🤣

**Comment by Carlgo11** [comment]
> Or just get rid of all the JavaScript

![](https://user-images.githubusercontent.com/3535780/81588447-cd8c2200-93b8-11ea-9962-8092fc83a508.gif)

**Comment by jamcat22** [comment]
![Legally Blonde - Elle Woods "What, like it's hard?"](https://user-images.githubusercontent.com/1897053/81589508-b9273580-9376-11ea-83bd-eb0d2c7f3071.gif)

**Comment by Carlgo11** [comment]
Does this work?  
I had to set the link to bold and white because blue made it barely visible for some reason 🤔 

![screenshot](https://user-images.githubusercontent.com/3535780/81590558-43918880-93bb-11ea-87b4-28a140947b6f.png)

**Comment by jamcat22** [comment]
Looks goody! Does it appear on all pages, and does it scale down on mobile?

**Comment by Carlgo11** [comment]
iPad:
<img src="https://user-images.githubusercontent.com/3535780/81590998-feba2180-93bb-11ea-905f-d3e242e44fdc.png" width="50%">

iPhone X:
<img src="https://user-images.githubusercontent.com/3535780/81591029-0ed20100-93bc-11ea-9561-4a89ac63348c.png" width="50%">

**Comment by Carlgo11** [comment]
Nokia 8110 4G:  

![](https://user-images.githubusercontent.com/3535780/81591217-62444f00-93bc-11ea-9aad-a26429ffc3ba.png)
